name = "Knowledge Planet"
description = "简约亮色个人知识星球主题"
license = "MIT"
min_version = "0.123.0"
max_version = ""

[author]
  name = "Lee"
  email = "hellohelloliying@yeah.net"

[formats]
  enable = ["HTML", "JSON", "RSS"]